/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;
import vistas.Productos;
import controlador.Metodos;
import rojerusan.RSPanelsSlider;
import static vistas.Productos.cbox_categoria;
/**
 *
 * @author ArtemSupa
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    int x,y;
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        
       
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelBorderGradient1 = new RSMaterialComponent.RSPanelBorderGradient();
        btn_home = new RSMaterialComponent.RSButtonMaterialIconOne();
        btn_ventas = new RSMaterialComponent.RSButtonMaterialIconOne();
        btn_compras = new RSMaterialComponent.RSButtonMaterialIconOne();
        btn_productos2 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSPanelMaterialImage1 = new RSMaterialComponent.RSPanelMaterialImage();
        btn_minimizar = new RSMaterialComponent.RSButtonIconOne();
        jPanel1 = new javax.swing.JPanel();
        btn_cerrar = new RSMaterialComponent.RSButtonIconOne();
        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setUndecorated(true);
        setResizable(false);

        rSPanelBorderGradient1.setBorderBottom(false);
        rSPanelBorderGradient1.setBorderLeft(false);
        rSPanelBorderGradient1.setBorderRight(false);
        rSPanelBorderGradient1.setBorderTop(false);
        rSPanelBorderGradient1.setColorPrimario(new java.awt.Color(255, 153, 153));
        rSPanelBorderGradient1.setColorSecundario(new java.awt.Color(255, 102, 153));
        rSPanelBorderGradient1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_home.setBackground(new java.awt.Color(255, 153, 153));
        btn_home.setText("Home");
        btn_home.setBackgroundHover(new java.awt.Color(255, 51, 204));
        btn_home.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        rSPanelBorderGradient1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 190, -1));

        btn_ventas.setBackground(new java.awt.Color(255, 153, 153));
        btn_ventas.setText("Ventas");
        btn_ventas.setBackgroundHover(new java.awt.Color(255, 51, 204));
        btn_ventas.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOCAL_ATM);
        btn_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ventasActionPerformed(evt);
            }
        });
        rSPanelBorderGradient1.add(btn_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 190, -1));

        btn_compras.setBackground(new java.awt.Color(255, 153, 153));
        btn_compras.setText("Compras");
        btn_compras.setBackgroundHover(new java.awt.Color(255, 51, 204));
        btn_compras.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOCAL_GROCERY_STORE);
        btn_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comprasActionPerformed(evt);
            }
        });
        rSPanelBorderGradient1.add(btn_compras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 190, -1));

        btn_productos2.setBackground(new java.awt.Color(255, 153, 153));
        btn_productos2.setText("Productos");
        btn_productos2.setBackgroundHover(new java.awt.Color(255, 51, 204));
        btn_productos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productos2ActionPerformed(evt);
            }
        });
        rSPanelBorderGradient1.add(btn_productos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 190, -1));

        rSPanelMaterialImage1.setBackground(new java.awt.Color(255, 102, 153));
        rSPanelMaterialImage1.setBgShade(new java.awt.Color(255, 102, 153));
        rSPanelMaterialImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoscarletSinCirculo.png"))); // NOI18N
        rSPanelMaterialImage1.setShadowBottom(false);
        rSPanelMaterialImage1.setShadowLeft(false);
        rSPanelMaterialImage1.setShadowRight(false);
        rSPanelMaterialImage1.setShadowTop(false);

        javax.swing.GroupLayout rSPanelMaterialImage1Layout = new javax.swing.GroupLayout(rSPanelMaterialImage1);
        rSPanelMaterialImage1.setLayout(rSPanelMaterialImage1Layout);
        rSPanelMaterialImage1Layout.setHorizontalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        rSPanelMaterialImage1Layout.setVerticalGroup(
            rSPanelMaterialImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        rSPanelBorderGradient1.add(rSPanelMaterialImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 190));

        btn_minimizar.setBackground(new java.awt.Color(255, 204, 204));
        btn_minimizar.setForeground(new java.awt.Color(0, 0, 0));
        btn_minimizar.setBackgroundHover(new java.awt.Color(0, 0, 0));
        btn_minimizar.setForegroundText(new java.awt.Color(0, 0, 0));
        btn_minimizar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REMOVE);
        btn_minimizar.setSizeIcon(20.0F);
        btn_minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimizarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        btn_cerrar.setBackground(new java.awt.Color(255, 204, 204));
        btn_cerrar.setForeground(new java.awt.Color(0, 0, 0));
        btn_cerrar.setBackgroundHover(new java.awt.Color(0, 0, 0));
        btn_cerrar.setForegroundText(new java.awt.Color(0, 0, 0));
        btn_cerrar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        btn_cerrar.setSizeIcon(20.0F);
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 204, 204));
        rSPanelMaterial1.setShadowBottom(false);
        rSPanelMaterial1.setShadowLeft(false);
        rSPanelMaterial1.setShadowRight(false);
        rSPanelMaterial1.setShadowTop(false);

        javax.swing.GroupLayout rSPanelMaterial1Layout = new javax.swing.GroupLayout(rSPanelMaterial1);
        rSPanelMaterial1.setLayout(rSPanelMaterial1Layout);
        rSPanelMaterial1Layout.setHorizontalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        rSPanelMaterial1Layout.setVerticalGroup(
            rSPanelMaterial1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rSPanelBorderGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1070, 1070, 1070)
                        .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelBorderGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimizarActionPerformed
        this.setExtendedState(1);
    }//GEN-LAST:event_btn_minimizarActionPerformed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
       this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed

    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ventasActionPerformed

    }//GEN-LAST:event_btn_ventasActionPerformed

    private void btn_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comprasActionPerformed
      
    }//GEN-LAST:event_btn_comprasActionPerformed

    private void btn_productos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productos2ActionPerformed
        MenuProductosF menprodf = new MenuProductosF();
        menprodf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_productos2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconOne btn_cerrar;
    public RSMaterialComponent.RSButtonMaterialIconOne btn_compras;
    public RSMaterialComponent.RSButtonMaterialIconOne btn_home;
    private RSMaterialComponent.RSButtonIconOne btn_minimizar;
    public RSMaterialComponent.RSButtonMaterialIconOne btn_productos2;
    public RSMaterialComponent.RSButtonMaterialIconOne btn_ventas;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSPanelBorderGradient rSPanelBorderGradient1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private RSMaterialComponent.RSPanelMaterialImage rSPanelMaterialImage1;
    // End of variables declaration//GEN-END:variables
}
