/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.Metodos;
import java.awt.Image;
import java.io.File;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.Producto;

/**
 *
 * @author ArtemSupa
 */
public class Productos extends javax.swing.JPanel {
    
    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        Metodos met = new Metodos();
        met.ConsultaComboboxCategoria(cbox_categoria);
    }
    
    
    
    
    private void limpiarCajasDatos(){
    
    txt_nombre_producto1.setText("");
    txt_valor_compra1.setText("");
    txt_valor_venta1.setText("");
    cbox_categoria.setSelectedIndex(0);
            
    }
    
    public int CambiaInt(String Valor ){
        int res = 0;

        try{

            res=Integer.parseInt(Valor);

        }catch(Exception e){
            System.out.println("Error: "+e.getMessage());   
            return 0;
        }
        return res; 
    } 
    
    public boolean validacionProductos(){
        
        if(txt_nombre_producto1.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe ingresar un nombre de producto");
            txt_nombre_producto1.requestFocus();
            return false;
        }
        
        if(txt_valor_compra1.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe ingresar un valor de compra");
            txt_valor_compra1.requestFocus();
            return false;
        }else{
            if(CambiaInt(txt_valor_compra1.getText())<0){  
                JOptionPane.showMessageDialog(null,"El valor de compra debe ser mayor o igual a 0");
                txt_valor_compra1.requestFocus();
                return false;
            }
        
        }
        
        if(txt_valor_venta1.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe ingresar un valor de venta");
            txt_valor_venta1.requestFocus();
            return false;
        }else{
            if(CambiaInt(txt_valor_venta1.getText())<0){  
                JOptionPane.showMessageDialog(null,"El valor de venta debe ser mayor o igual a 0");
                txt_valor_venta1.requestFocus();
                return false;
            }
        
        }
        
        if(cbox_categoria.getSelectedItem().equals("Seleccione una categoria")){
            JOptionPane.showMessageDialog(null,"Debe ingresar una categoria de producto");
            cbox_categoria.requestFocus();
            return false;
        }
        
    
    return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        txt_nombre_producto1 = new RSMaterialComponent.RSTextFieldTwo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_valor_compra1 = new RSMaterialComponent.RSTextFieldTwo();
        jLabel3 = new javax.swing.JLabel();
        txt_valor_venta1 = new RSMaterialComponent.RSTextFieldTwo();
        cbox_categoria = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel4 = new javax.swing.JLabel();
        txt_imagen1 = new javax.swing.JLabel();
        btn_grabar1 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo2 = new RSMaterialComponent.RSButtonMaterialIconTwo();

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 204, 204));
        rSPanelMaterial1.setShadowBottom(false);
        rSPanelMaterial1.setShadowLeft(false);
        rSPanelMaterial1.setShadowRight(false);
        rSPanelMaterial1.setShadowTop(false);
        rSPanelMaterial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombre_producto1.setBackground(new java.awt.Color(255, 204, 204));
        txt_nombre_producto1.setForeground(new java.awt.Color(0, 0, 0));
        txt_nombre_producto1.setBorderColor(new java.awt.Color(0, 0, 0));
        txt_nombre_producto1.setPhColor(new java.awt.Color(102, 102, 102));
        txt_nombre_producto1.setPlaceholder("NombreEjemplo");
        txt_nombre_producto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_producto1ActionPerformed(evt);
            }
        });
        txt_nombre_producto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nombre_producto1KeyPressed(evt);
            }
        });
        rSPanelMaterial1.add(txt_nombre_producto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 190, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre de producto");
        rSPanelMaterial1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Valor de compra");
        rSPanelMaterial1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txt_valor_compra1.setBackground(new java.awt.Color(255, 204, 204));
        txt_valor_compra1.setForeground(new java.awt.Color(0, 0, 0));
        txt_valor_compra1.setBorderColor(new java.awt.Color(0, 0, 0));
        txt_valor_compra1.setPhColor(new java.awt.Color(102, 102, 102));
        txt_valor_compra1.setPlaceholder("$1000");
        txt_valor_compra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_valor_compra1ActionPerformed(evt);
            }
        });
        txt_valor_compra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_valor_compra1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_valor_compra1KeyTyped(evt);
            }
        });
        rSPanelMaterial1.add(txt_valor_compra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Categoria");
        rSPanelMaterial1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txt_valor_venta1.setBackground(new java.awt.Color(255, 204, 204));
        txt_valor_venta1.setForeground(new java.awt.Color(0, 0, 0));
        txt_valor_venta1.setBorderColor(new java.awt.Color(0, 0, 0));
        txt_valor_venta1.setPhColor(new java.awt.Color(102, 102, 102));
        txt_valor_venta1.setPlaceholder("$1000");
        txt_valor_venta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_valor_venta1ActionPerformed(evt);
            }
        });
        txt_valor_venta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_valor_venta1KeyTyped(evt);
            }
        });
        rSPanelMaterial1.add(txt_valor_venta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, 40));

        cbox_categoria.setBackground(new java.awt.Color(255, 204, 204));
        cbox_categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una categoria" }));
        cbox_categoria.setToolTipText("");
        cbox_categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbox_categoriaMouseClicked(evt);
            }
        });
        cbox_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_categoriaActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(cbox_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 190, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Valor de venta");
        rSPanelMaterial1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txt_imagen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_imagen1.setText("Foto");
        txt_imagen1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSPanelMaterial1.add(txt_imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 490, 290));

        btn_grabar1.setBackground(new java.awt.Color(255, 153, 204));
        btn_grabar1.setText("Guardar producto");
        btn_grabar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_grabar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_grabar1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btn_grabar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grabar1ActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(btn_grabar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 220, -1));

        rSButtonMaterialIconTwo2.setBackground(new java.awt.Color(255, 153, 204));
        rSButtonMaterialIconTwo2.setText("Seleccionar imagen");
        rSButtonMaterialIconTwo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonMaterialIconTwo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSButtonMaterialIconTwo2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.IMAGE);
        rSButtonMaterialIconTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo2ActionPerformed(evt);
            }
        });
        rSPanelMaterial1.add(rSButtonMaterialIconTwo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 470, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelMaterial1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombre_producto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_producto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_producto1ActionPerformed

    private void txt_valor_compra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_valor_compra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_valor_compra1ActionPerformed

    private void txt_valor_venta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_valor_venta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_valor_venta1ActionPerformed

    private void cbox_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_categoriaActionPerformed
    File fichero;
    private void btn_grabar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grabar1ActionPerformed
        if(validacionProductos()==false){
          return;
        }
        
        Metodos met = new Metodos();
        Producto objProducto = new Producto();
        String categoriaID = cbox_categoria.getSelectedItem().toString();
        
        objProducto.setNombreProd(txt_nombre_producto1.getText());
        objProducto.setValorCompraProd(Integer.parseInt(txt_valor_compra1.getText()));
        objProducto.setValorVentaProd(Integer.parseInt(txt_valor_venta1.getText()));
        objProducto.setStockProd(Integer.parseInt("0"));   
        objProducto.setEstadoProd("Activo");
        objProducto.setIdCategoriaProd(met.ObtenerIdCategoria(categoriaID));
        
        String id1  = txt_nombre_producto1.getText().substring(0,3);
        int largoultimo = txt_nombre_producto1.getText().length();
        String id2  = txt_nombre_producto1.getText().substring(largoultimo-3,largoultimo);
        String id3  = cbox_categoria.getSelectedItem().toString().substring(0,4);
        Calendar c1 = Calendar.getInstance();
        String dia = Integer.toString(c1.get(Calendar.DATE));
        int mesnumero = c1.get(Calendar.MONTH);
        int total =mesnumero+1;
        String mes = Integer.toString(total);
        String annio = Integer.toString(c1.get(Calendar.YEAR));
        String hora = Integer.toString(c1.get(Calendar.HOUR));
        String minutos = Integer.toString(c1.get(Calendar.MINUTE));
        String idproducto = id1+id2+id3+dia+mes+annio+hora+minutos;
        objProducto.setCodigoProd(idproducto);
        
        
        
           
        
        if(txt_imagen1.getText()=="Foto"){
            boolean resultado = met.InsertarDatosProd(objProducto);
            if(resultado==true){
            JOptionPane.showMessageDialog(null, "Producto Ingresado Exitosamente");
            limpiarCajasDatos();
            }else{
                JOptionPane.showMessageDialog(null, "Error al ingresar registro de producto");
            }
            
        }else{
            boolean resultado = met.InsertarDatosProd(objProducto);
            if(resultado==true){
            String ficheroConvert = fichero.toString();
            byte[] b = ficheroConvert.getBytes();
            objProducto.setImagenProd(b);
            objProducto.setCodigoProd(idproducto);
            met.InsertarImagenProd(objProducto, ficheroConvert);    
            JOptionPane.showMessageDialog(null, "Producto Ingresado Exitosamente");
            limpiarCajasDatos();
            }else{
                JOptionPane.showMessageDialog(null, "Error al ingresar registro de producto");
            }
            
        }
        
    }//GEN-LAST:event_btn_grabar1ActionPerformed

    private void rSButtonMaterialIconTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo2ActionPerformed
        int resultado;
        
        CargarFoto cfoto = new CargarFoto();
        FileNameExtensionFilter filtroimagen = new FileNameExtensionFilter("JPG/PNG","png","jpg");
        cfoto.FileCargarFoto.setFileFilter(filtroimagen);
        resultado = cfoto.FileCargarFoto.showOpenDialog(null);
        if ( JFileChooser.APPROVE_OPTION==resultado){
            fichero = cfoto.FileCargarFoto.getSelectedFile();
            String ficheroConvert = fichero.toString();
            byte[] b = ficheroConvert.getBytes();
            Metodos met = new Metodos();
            Producto objProducto = new Producto();
            objProducto.setImagenProd(b);
            //objProducto.setCodigoProd(idproducto);
            
            try{
                ImageIcon icono = new ImageIcon(fichero.toString());
                Icon iconoL = new ImageIcon(icono.getImage().getScaledInstance(txt_imagen1.getWidth(),txt_imagen1.getHeight(),Image.SCALE_DEFAULT));
                txt_imagen1.setText(null);
                txt_imagen1.setIcon(iconoL);
                //met.InsertarImagenProd(objProducto, ficheroConvert);
            }catch (Exception ex){
                JOptionPane.showMessageDialog(null,"No se pudo abrir la imagen"+ex);
            }
        }
        
    }//GEN-LAST:event_rSButtonMaterialIconTwo2ActionPerformed

    private void txt_nombre_producto1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombre_producto1KeyPressed

    }//GEN-LAST:event_txt_nombre_producto1KeyPressed

    private void txt_valor_compra1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_valor_compra1KeyPressed
        
    }//GEN-LAST:event_txt_valor_compra1KeyPressed

    private void txt_valor_compra1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_valor_compra1KeyTyped
        char datostipear = evt.getKeyChar();
        if((datostipear<'0' || datostipear>'9')) evt.consume();
    }//GEN-LAST:event_txt_valor_compra1KeyTyped

    private void txt_valor_venta1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_valor_venta1KeyTyped
        char datostipear = evt.getKeyChar();
        if((datostipear<'0' || datostipear>'9')) evt.consume();
    }//GEN-LAST:event_txt_valor_venta1KeyTyped

    private void cbox_categoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_categoriaMouseClicked
       
    }//GEN-LAST:event_cbox_categoriaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconTwo btn_grabar1;
    public static RSMaterialComponent.RSComboBoxMaterial cbox_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo2;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private javax.swing.JLabel txt_imagen1;
    private RSMaterialComponent.RSTextFieldTwo txt_nombre_producto1;
    private RSMaterialComponent.RSTextFieldTwo txt_valor_compra1;
    private RSMaterialComponent.RSTextFieldTwo txt_valor_venta1;
    // End of variables declaration//GEN-END:variables

   
}
