/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;


import controlador.Metodos;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Producto;

/**
 *
 * @author ArtemSupa
 */
public class PROD_editProd extends javax.swing.JFrame {

    /**
     * Creates new form PROD_editProd
     */
    
     int x,y;
    private TableRowSorter trsfiltro;
    public PROD_editProd() {
        initComponents();
        Metodos met = new Metodos();
        met.ConsultaComboboxCategoria(cbox_categoria);
        LlenaGrilla();
    }
public void LlenaGrilla(){
    
    DefaultTableModel modeloLista = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int col)
            {
                return false;
            }
        };
      
        ArrayList<Object> Nombrecolumna = new ArrayList<Object>();
        Nombrecolumna.add("Id");
        Nombrecolumna.add("Nombre");
        Nombrecolumna.add("Valor compra");
        Nombrecolumna.add("Valor venta");
        Nombrecolumna.add("Stock");
        Nombrecolumna.add("Categoria");
        Nombrecolumna.add("Estado");
        for (Object column :Nombrecolumna){
            modeloLista.addColumn(column);
        }
        this.tbl_grillaProd.setModel(modeloLista);


        
        Metodos met = new Metodos();
        ArrayList<Producto> listProducto = new ArrayList<Producto>();
        
        listProducto = met.ListarDatosProductocompleto();
        
        
        if(txt_filtronomprod.getText().equals("")){
         
        }else{
            
            if(listProducto.size()<=0){
                JOptionPane.showMessageDialog(null, "Nombre de producto no existe en nuestros registros");
                txt_filtronomprod.setText("");
                txt_filtronomprod.requestFocus();
            }
        }    
        Producto prod = new Producto();
        Iterator<Producto> intProducto = listProducto.iterator();
        while(intProducto.hasNext()){
            
            Producto elemento=intProducto.next();
            String resulCate = met.ObtenerNombreCategoria(elemento.getIdCategoriaProd());
            
            Object[] vi = new Object[]{elemento.getCodigoProd(),elemento.getNombreProd(),elemento.getValorCompraProd(),elemento.getValorVentaProd(),elemento.getStockProd(),resulCate,elemento.getEstadoProd()};
            
            modeloLista.addRow(vi);
            
        }    
        
        this.tbl_grillaProd.setModel(modeloLista);
    
    
    
    }     
public void filtro() {
        
        trsfiltro.setRowFilter(RowFilter.regexFilter("(?i)"+txt_filtronomprod.getText(), 1));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelMaterial1 = new RSMaterialComponent.RSPanelMaterial();
        cbox_categoria = new RSMaterialComponent.RSComboBoxMaterial();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_grillaProd = new RSMaterialComponent.RSTableMetroCustom();
        txt_filtronomprod = new RSMaterialComponent.RSTextFieldIconTwo();
        rSButtonIcon_new1 = new newscomponents.RSButtonIcon_new();
        rSButtonIconOne1 = new RSMaterialComponent.RSButtonIconOne();
        rSButtonIconOne2 = new RSMaterialComponent.RSButtonIconOne();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelMaterial1.setBackground(new java.awt.Color(255, 204, 204));
        rSPanelMaterial1.setShadowBottom(false);
        rSPanelMaterial1.setShadowLeft(false);
        rSPanelMaterial1.setShadowRight(false);
        rSPanelMaterial1.setShadowTop(false);
        rSPanelMaterial1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbox_categoria.setBackground(new java.awt.Color(255, 204, 204));
        cbox_categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una categoria" }));
        cbox_categoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbox_categoriaItemStateChanged(evt);
            }
        });
        rSPanelMaterial1.add(cbox_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 240, -1));

        tbl_grillaProd.setForeground(new java.awt.Color(255, 204, 204));
        tbl_grillaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_grillaProd.setBackgoundHead(new java.awt.Color(255, 153, 153));
        tbl_grillaProd.setBackgoundHover(new java.awt.Color(255, 102, 102));
        tbl_grillaProd.setColorBorderHead(new java.awt.Color(255, 204, 204));
        tbl_grillaProd.setColorBorderRows(new java.awt.Color(255, 204, 204));
        tbl_grillaProd.setColorPrimary(new java.awt.Color(255, 102, 102));
        tbl_grillaProd.setColorPrimaryText(new java.awt.Color(255, 255, 255));
        tbl_grillaProd.setColorSecondary(new java.awt.Color(255, 153, 102));
        tbl_grillaProd.setColorSecundaryText(new java.awt.Color(255, 255, 255));
        tbl_grillaProd.setGridColor(new java.awt.Color(255, 204, 204));
        tbl_grillaProd.setSelectionBackground(new java.awt.Color(0, 255, 204));
        tbl_grillaProd.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbl_grillaProd.setShowHorizontalLines(true);
        tbl_grillaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_grillaProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_grillaProd);

        rSPanelMaterial1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1240, 410));

        txt_filtronomprod.setBackground(new java.awt.Color(255, 204, 204));
        txt_filtronomprod.setForeground(new java.awt.Color(0, 0, 0));
        txt_filtronomprod.setBorderColor(new java.awt.Color(0, 0, 0));
        txt_filtronomprod.setColorIcon(new java.awt.Color(255, 255, 255));
        txt_filtronomprod.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txt_filtronomprod.setPlaceholder("Nombre de producto");
        txt_filtronomprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filtronomprodActionPerformed(evt);
            }
        });
        txt_filtronomprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_filtronomprodKeyTyped(evt);
            }
        });
        rSPanelMaterial1.add(txt_filtronomprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 320, -1));

        getContentPane().add(rSPanelMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1330, 550));

        rSButtonIcon_new1.setBackground(new java.awt.Color(255, 204, 204));
        rSButtonIcon_new1.setText("Atrás");
        rSButtonIcon_new1.setBackgroundHover(new java.awt.Color(201, 162, 162));
        rSButtonIcon_new1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.KEYBOARD_ARROW_LEFT);
        rSButtonIcon_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIcon_new1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonIcon_new1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        rSButtonIconOne1.setBackground(new java.awt.Color(255, 204, 204));
        rSButtonIconOne1.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonIconOne1.setBackgroundHover(new java.awt.Color(0, 0, 0));
        rSButtonIconOne1.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REMOVE);
        rSButtonIconOne1.setSizeIcon(20.0F);
        rSButtonIconOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconOne1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 0, 27, 24));

        rSButtonIconOne2.setBackground(new java.awt.Color(255, 204, 204));
        rSButtonIconOne2.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonIconOne2.setBackgroundHover(new java.awt.Color(0, 0, 0));
        rSButtonIconOne2.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonIconOne2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        rSButtonIconOne2.setSizeIcon(20.0F);
        rSButtonIconOne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconOne2ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonIconOne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 27, 24));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setOpaque(true);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIcon_new1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIcon_new1ActionPerformed
        MenuProductosF menprof = new MenuProductosF();
        menprof.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonIcon_new1ActionPerformed

    private void rSButtonIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconOne1ActionPerformed
        this.setExtendedState(1);
    }//GEN-LAST:event_rSButtonIconOne1ActionPerformed

    private void rSButtonIconOne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconOne2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSButtonIconOne2ActionPerformed
String CodigoProd = "";
    private void tbl_grillaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_grillaProdMouseClicked
        if(evt.getClickCount()==2){
            int seleccionar= tbl_grillaProd.rowAtPoint(evt.getPoint());
            String CodigoProd = String.valueOf(tbl_grillaProd.getValueAt(seleccionar, 0));
            PROD_PantEditar pantallaedita;
            try {
                pantallaedita = new PROD_PantEditar(CodigoProd);
                pantallaedita.setVisible(true);
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(PROD_editProd.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
        
    }//GEN-LAST:event_tbl_grillaProdMouseClicked

    private void txt_filtronomprodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtronomprodKeyTyped

        txt_filtronomprod.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                String cadena = (txt_filtronomprod.getText());
                txt_filtronomprod.setText(cadena);
                repaint();
                filtro();
            }
        });

        trsfiltro = new TableRowSorter(tbl_grillaProd.getModel());
        tbl_grillaProd.setRowSorter(trsfiltro);
    }//GEN-LAST:event_txt_filtronomprodKeyTyped

    private void txt_filtronomprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filtronomprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filtronomprodActionPerformed

    private void cbox_categoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbox_categoriaItemStateChanged
       
       String query = cbox_categoria.getSelectedItem().toString();
       TableRowSorter<DefaultTableModel> tr = new TableRowSorter(tbl_grillaProd.getModel());
       tbl_grillaProd.setRowSorter(tr);
       
       if(query !="Seleccione una categoria"){
           tr.setRowFilter(RowFilter.regexFilter(query, 5));
       
       
       }else{
           tbl_grillaProd.setRowSorter(tr);
       }
    }//GEN-LAST:event_cbox_categoriaItemStateChanged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
       this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROD_editProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROD_editProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROD_editProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROD_editProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROD_editProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSComboBoxMaterial cbox_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne1;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne2;
    private newscomponents.RSButtonIcon_new rSButtonIcon_new1;
    private RSMaterialComponent.RSPanelMaterial rSPanelMaterial1;
    private RSMaterialComponent.RSTableMetroCustom tbl_grillaProd;
    private RSMaterialComponent.RSTextFieldIconTwo txt_filtronomprod;
    // End of variables declaration//GEN-END:variables
}
